### ISSUE TITLE
Switching to Normal or Quick Cast Mode does not switch properly

### ISSUE THREAD

**Issue by Khanfluence** [loopuleasa/super-compact-dota2-keybinds#12]
To concisely describe the issue, you must switch modes and then SPACE+cast an ability for the switch take effect for a non-modifier cast. Example steps are below:

Starting state:
- Pressing Q quick casts ability 1.
- Pressing SPACE+Q normal casts ability 1.
- (Pressing F7 switches modes).

Current behavior:
- Press F7.
- Pressing Q quick casts ability 1. *
- Pressing SPACE+Q quick casts ability 1.
- Pressing Q a second time normal casts ability 1.
- Press F7.
- Pressing Q normal casts ability 1. *
- Pressing SPACE+Q normal casts ability 1.
- Pressing Q a second time quick casts ability 1.

Expected behavior:
- Press F7.
- Pressing Q normal casts ability 1.
- Pressing SPACE+Q quick casts ability 1.
- Press F7.
- Pressing Q quick casts ability 1.
- Pressing SPACE+Q normal casts ability 1.

Please note the starred bullets. At these steps, you can press Q any number of times (including zero) and it will exhibit the same behavior until SPACE+Q is pressed (after which the behavior for Q changes).

**Comment by loopuleasa** [comment]
Fixed
