### ISSUE TITLE
New dota2 6.84 patch seem to break some functionalities

### ISSUE THREAD

**Issue by loopuleasa** [loopuleasa/super-compact-dota2-keybinds#14]
Please report the issues you encounter here.

**Comment by loopuleasa** [comment]
One issue that seems to be unresolved is that you can't double click on wards to change them.

**Comment by ZdravkoZaprev** [comment]
Man can u say me how i can made keybindg for Invoker ctrl + D - for Meteor ctrl + T - for sunstrike, because i try everything but can't do this ...

**Comment by loopuleasa** [comment]
I won't support extensive macros like the invoker ones because they're unfair.
You're pressing a keystroke and the program performs about 6 game actions for you which isn't fair.

My philosophy for these configs is that 1 keystroke = 1 game action.

The layout is just optimal as it can be.

**Comment by ZdravkoZaprev** [comment]
Thank you for fast answer, but nevermind bro i did it with hard work .. If
u want to play Dota2 reply :)


2015-05-10 21:54 GMT+03:00 Lup <notifications@github.com>:
