### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by CounterOFKills** [loopuleasa/super-compact-dota2-keybinds#18]
The coin sound plays so the autoexec works. but none of the keybinds are working. Anyone else having this problem? Any fixes?

**Comment by KLE88** [comment]
I'm also having this issue but i cant be sure i installed it correctly could you possibly make a video showing how to install it because i'm quite confused, sorry!

**Comment by Crowbahr** [comment]
I'm having the same issue and did the installation correctly. It doesn't work.

I've deleted all my bindings, placed them in the correct folder, replaced game_convars.cfg etc but nothing actually binds. The only thing I can get is console. Stop, attack move, hell even "Enter" don't work.

**Comment by tgfish** [comment]
Same.. could really use some help here.

**Comment by tgfish** [comment]
Make sure you have in the right directory (NEW):

OLD: Program Files (x86)\Steam\SteamApps\common\dota 2 beta\dota\cfg
NEW: Program Files (x86)\Steam\SteamApps\common\dota 2 beta\game\dota\cfg

**Comment by CounterOFKills** [comment]
it is ib ht right directory

**Comment by Crowbahr** [comment]
Yeah mine is all in the right directory. 

Refactoring the old bindings I had currently works but this set doesn't. Unsure why not.

**Comment by loopuleasa** [comment]
My cfg directory looks like this, make sure it's the same
http://i.imgur.com/g05hHyl.png

**Comment by CounterOFKills** [comment]
ok thanks, spotted the mistake
