### ISSUE TITLE
Dota 2 Reborn Won't Open

### ISSUE THREAD

**Issue by melivion** [loopuleasa/super-compact-dota2-keybinds#19]
I have a really old pc, but I am still able to run dota 2 just fine, but whenever i hit play on dota 2 reborn it takes me to the loading screen and then shuts down with no error message. I've tried everything people said, the lauch options thing, restart pc etc. And I don't have the 64 bit folder either, so that can't happen too. I don't think is my pc because a lot of people got this problem, I hope it's a bug, going to be fixed.

**Comment by loopuleasa** [comment]
Don't think it's related to my configs. Try removing my stuff from the cfg folder to see if it's related.
