### ISSUE TITLE
Use chat wheel commands for right side of keyboard

### ISSUE THREAD

**Issue by KaiSforza** [loopuleasa/super-compact-dota2-keybinds#21]
Instead of using text, where possible just use chat commands so they're translated into the client language using things detailed here:

http://dota2.gamepedia.com/Chat_Wheel

**Comment by loopuleasa** [comment]
Yep, but what if you want to say "Davai"
Chat wheel doesn't have Davai.

**Comment by KaiSforza** [comment]
Well, you can keep the [davai] one in there, but for things like "Missing top!", etc. this will make the characters speak as well as things be translated properly.

**Comment by KaiSforza** [comment]
Looks like #27 and #28 fix this.

**Comment by loopuleasa** [comment]
Gonna handle them.
