### ISSUE TITLE
How to make camera move instantly

### ISSUE THREAD

**Issue by CounterOFKills** [loopuleasa/super-compact-dota2-keybinds#24]
I am currently using the middle mouse button for normal camera movement, but there is a delay between when I move the mouse and when the camera moves.  How can I make it instant? I looked through the files but couldn't find any option for it.

**Comment by loopuleasa** [comment]
Middle mouse camera drag is a dota option, and not something I implemented.
Make sure you have no frame lag.

**Comment by xackoff** [comment]
Turn off VSync, you are experiencing global input lag.
